# Generated by Django 6.0.3 on 2026-05-30 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(default='diabetes', max_length=50)),
                ('prediction', models.CharField(choices=[('High Risk', 'High Risk'), ('Low Risk', 'Low Risk')], max_length=20)),
                ('confidence', models.FloatField()),
                ('diabetes_probability', models.FloatField()),
                ('input_data', models.JSONField(default=dict)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
