# -*- coding: utf-8 -*-
"""heart_disease_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSYQ3r04eku1OuzqHT19OYZdU8c4q2Ok
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib
from google.colab import files

print("Loading Kaggle 70k Cardiovascular Dataset...")
# Sourced from a reliable public repository containing the clean Kaggle cardio_train.csv
url = "https://raw.githubusercontent.com/caravanuden/cardio/master/cardio_train.csv"
df = pd.read_csv(url, sep=';')

# Convert age from days to years so it matches what our Django app calculates!
df['age'] = (df['age'] / 365).round().astype(int)

print(f"✅ Data loaded successfully! Total Records: {df.shape[0]} patients.")
display(df.head())

print("Before cleaning:", df.shape[0], "records")

# Clean Blood Pressure: Keep Systolic between 80 and 220, and Diastolic between 50 and 130
df = df[(df['ap_hi'] >= 80) & (df['ap_hi'] <= 220)]
df = df[(df['ap_lo'] >= 50) & (df['ap_lo'] <= 130)]

# Drop the 'id' column as it has no medical predictive value
X = df.drop(['id', 'cardio'], axis=1)
y = df['cardio'] # 1 = Heart Disease present, 0 = Healthy

# Split into Training (80%) and Testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("After outlier cleaning:", df.shape[0], "records split ready for training.")

print("1. Scaling biometric metrics...")
scaler_heart = StandardScaler()
X_train_scaled = scaler_heart.fit_transform(X_train)
X_test_scaled = scaler_heart.transform(X_test)

print("2. Training Cardiovascular Random Forest...")
# Tuned hyperparameters to prevent overfitting on the large dataset
heart_model = RandomForestClassifier(
    n_estimators=150,
    max_depth=10,
    min_samples_split=10,
    random_state=42
)
heart_model.fit(X_train_scaled, y_train)

# Evaluate performance
y_pred = heart_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n🎯 Heart Model Test Accuracy: {accuracy * 100:.2f}%\n")
print("📊 Full Classification Report:")
print(classification_report(y_test, y_pred))

# Test data representing different combinations of user values
custom_heart_test = {
    'Patient_Profile': ['Young Fit Individual', 'High Risk Profile (Obese + High BP)'],
    'age': [24, 56],
    'gender': [1, 2],       # 1 = Female, 2 = Male (Dataset Mapping)
    'height': [165, 175],   # in cm
    'weight': [58.0, 96.0], # in kg
    'ap_hi': [115, 160],    # Systolic blood pressure
    'ap_lo': [75, 100],     # Diastolic blood pressure
    'cholesterol': [1, 3],  # 1: Normal, 2: Above Normal, 3: High
    'gluc': [1, 2],         # 1: Normal, 2: Above Normal, 3: High
    'smoke': [0, 1],        # 0 = Non-smoker, 1 = Smoker
    'alco': [0, 0],         # Alcohol intake flag
    'active': [1, 0]        # 1 = Physically active, 0 = Sedentary
}

custom_df = pd.DataFrame(custom_heart_test)
features_only = custom_df.drop('Patient_Profile', axis=1)

# Scale using our heart scaler
features_scaled = scaler_heart.transform(features_only)

# Predict
preds = heart_model.predict(features_scaled)
probs = heart_model.predict_proba(features_scaled)

# Present beautifully
custom_df['AI Risk Status'] = ['⚠️ CARDIO RISK' if p == 1 else '✅ LOW RISK' for p in preds]
custom_df['Confidence %'] = [f"{max(prob)*100:.1f}%" for prob in probs]

display(custom_df[['Patient_Profile', 'age', 'ap_hi', 'weight', 'AI Risk Status', 'Confidence %']])

# Use clear names so they don't overwrite your diabetes model files!
model_file = 'heart_rf_model.pkl'
scaler_file = 'heart_scaler.pkl'

joblib.dump(heart_model, model_file)
joblib.dump(scaler_heart, scaler_file)

print("📁 Local pickle files generated successfully.")
files.download(model_file)
files.download(scaler_file)