# Generated by Django 6.0.3 on 2026-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
