# Generated by Django 6.0.3 on 2026-05-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_active_userprofile_alco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')])),
                ('sleep_quality', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')])),
                ('diet_quality', models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Great', 'Great')], max_length=20)),
                ('water_goal', models.BooleanField(default=False)),
                ('exercise_goal', models.BooleanField(default=False)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_checkins',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
