# Generated by Django 6.0.3 on 2026-05-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_healthlog_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='blood_sugar_mg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='step_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='water_intake_liters',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='healthlog',
            unique_together={('user', 'date')},
        ),
    ]
