# Generated by Django 6.0.3 on 2026-05-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_healthlog_blood_sugar_mg_healthlog_sleep_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('step_count', 'Step Count'), ('water_intake', 'Water Intake (Liters)'), ('sleep_hours', 'Sleep (Hours)'), ('weight_kg', 'Weight (kg)'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='users.healthgoal')),
            ],
            options={
                'db_table': 'goal_progress',
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
